# Generated by Django 2.1.5 on 2019-09-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_user_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(upload_to='Check_Image/')),
            ],
        ),
    ]
