# Generated by Django 2.1.5 on 2019-09-09 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_check_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check_image',
            old_name='user_image',
            new_name='image',
        ),
    ]
