# Generated by Django 2.1.5 on 2019-09-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_auto_20190910_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ManyToManyField(null=True, related_name='img', to='frontend.Image'),
        ),
    ]
