# Generated by Django 2.1.5 on 2019-09-10 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_auto_20190910_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='frontend.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ManyToManyField(related_name='img', to='frontend.Image'),
        ),
    ]
